# core
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "adoptopenjdk/openjdk"
tap "derailed/k9s"

# core utils
brew "ripgrep"
brew "stormssh"
brew "exa"
brew "bat"
brew "fd"
brew "tokei" # count lines of code
brew "tree"
brew "unrar"
brew "watch"
brew "wget"
brew "wrk"
brew "tldr"
brew "jq"
brew "htop"
brew "fzf"
brew "git"
brew "git-flow-avh"

brew "gnupg"
brew "libksba" # required by gnupg
brew "gmp" # required by gnupg

# cloud tools
brew "operator-sdk"
brew "helm"
brew "protobuf"
brew "kubernetes-cli"
brew "kustomize"
brew "kubectx"
brew "stern"
brew "ansible"
brew "derailed/k9s/k9s"

# terminal
brew "neovim"
brew "zsh-completions"
brew "git-delta"
brew "diff-so-fancy"
# langluage
brew "python@3.8"
brew "go"

brew "gradle"
brew "maven"

brew "node"

brew "rustup-init"
