live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xcd3131"
index = 17

[colors.bright]
black = "0x666666"
blue = "0x0451a5"
cyan = "0x0598bc"
green = "0x14ce14"
magenta = "0xbc05bc"
red = "0xcd3131"
white = "0x586069"
yellow = "0xb5ba00"

[colors.normal]
black = "0x697179"
blue = "0x0451a5"
cyan = "0x0598bc"
green = "0x14ce14"
magenta = "0xbc05bc"
red = "0xd03d3d"
white = "0x586069"
yellow = "0x6e7101"

[colors.primary]
background = "0xffffff"
foreground = "0x586069"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "JetBrainsMono NF"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono NF"
style = "ExtraLight"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = false
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
