env:
  TERM: xterm-256color
shell:
  program: /usr/bin/tmux
  args:
  - new-session
  - -A
  - -s
  - Lala
window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 0
    y: 0
  startup_mode: Maximized
  decorations: none
  dynamic_padding: false
scrolling:
  history: 10000
  multiplier: 3
font:
  size: 9
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Light
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
draw_bold_text_with_bright_colors: true
colors:
  primary:
    background: '0xffffff'
    foreground: '0x586069'

  normal:
    black:   '0x697179'
    red:     '0xd03d3d'
    green:   '0x14ce14'
    yellow:  '0x6e7101'
    blue:    '0x0451a5'
    magenta: '0xbc05bc'
    cyan:    '0x0598bc'
    white:   '0x586069'

  bright:
    black:   '0x666666'
    red:     '0xcd3131'
    green:   '0x14ce14'
    yellow:  '0xb5ba00'
    blue:    '0x0451a5'
    magenta: '0xbc05bc'
    cyan:    '0x0598bc'
    white:   '0x586069'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xcd3131' }
bell:
  animation: EaseOutExpo
  duration: 0
mouse_bindings:
  - mouse: Middle
    action: PasteSelection
mouse:
  double_click:
    threshold: 300
  triple_click:
    threshold: 300
  hide_when_typing: true
cursor:
  style: Block
  unfocused_hollow: true
live_config_reload: true
