[general]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true


[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "None"
dynamic_padding = false
startup_mode = "Maximized"
# dimensions = { columns = 300, lines = 100}

[window.padding]
x = 0
y = 0
