
[core]
color-theme = "Lapce Light"
modal = true
icon-theme = "Material Icons"

[ui]
font-family = "Roboto"

[editor]
font-family = "JetBrainsMono NFM Light"
font-size = 14

[terminal]
font-family = "JetBrainsMono NFM Light"
