env:
  TERM: xterm-256color
  TERM_PROGRAM: Alacritty
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

shell:
  program: /usr/local/bin/tmux
  args:
    - new-session
    - -A
    - -s
    - Lala

window:
  dimensions:
    columns: 0
    lines: 0
  dynamic_padding: false

  padding:
    x: 0
    y: 0

  startup_mode: Maximized # SimpleFullscreen
  decorations: none
  opacity: 1.0

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

# Font configuration (changes require restart)
font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: ExtraLight
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: ExtraLight
  italic:
    family: JetBrainsMono Nerd Font Mono
    style: ExtraLight

  # Point size
  size: 13

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

  # Thin stroke font rendering (OS X only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina screens
  # it is recommended to set `use_thin_strokes` to `false`
  use_thin_strokes: true

draw_bold_text_with_bright_colors: true
colors:
  # Default colors
  primary:
    background: '0xffffff'
    foreground: '0x586069'

  # Normal colors
  normal:
    black:   '0x697179'
    red:     '0xd03d3d'
    green:   '0x14ce14'
    yellow:  '0x6e7101'
    blue:    '0x0451a5'
    magenta: '0xbc05bc'
    cyan:    '0x0598bc'
    white:   '0x586069'

  # Bright colors
  bright:
    black:   '0x666666'
    red:     '0xcd3131'
    green:   '0x14ce14'
    yellow:  '0xb5ba00'
    blue:    '0x0451a5'
    magenta: '0xbc05bc'
    cyan:    '0x0598bc'
    white:   '0x586069'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xcd3131' }

bell:
  animation: EaseOutExpo
  duration: 0

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

cursor:
  style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

# Live config reload (changes require restart)
live_config_reload: true

key_bindings:
  - { key: N, mods: Command, action: SpawnNewInstance }

  # tmux key binding
  - { key: D, mods: Command, chars: "\x02\x76" }
  - { key: D, mods: Command|Shift, chars: "\x02\x73" }
  - { key: W, mods: Command, chars: "\x02\x78" }
  - { key: H, mods: Command, chars: "\x02\x68" }
  - { key: J, mods: Command, chars: "\x02\x6a" }
  - { key: K, mods: Command, chars: "\x02\x6b" }
  - { key: L, mods: Command, chars: "\x02\x6c" }
  - { key: T, mods: Command, chars: "\x02\x63" }
  - { key: Key1, mods: Command, chars: "\x02\x31" }
  - { key: Key2, mods: Command, chars: "\x02\x32" }
  - { key: Key3, mods: Command, chars: "\x02\x33" }
  - { key: Key4, mods: Command, chars: "\x02\x34" }
  - { key: Key5, mods: Command, chars: "\x02\x35" }
  - { key: Key6, mods: Command, chars: "\x02\x36" }
  - { key: Key7, mods: Command, chars: "\x02\x37" }
  - { key: Key8, mods: Command, chars: "\x02\x38" }
  - { key: Key9, mods: Command, chars: "\x02\x39" }
  - { key: Left, mods: Command, chars: "\x02\x48" }
  - { key: Down, mods: Command, chars: "\x02\x4a" }
  - { key: Up, mods: Command, chars: "\x02\x4b" }
  - { key: Right, mods: Command, chars: "\x02\x4c" }
  - { key: "LBracket", mods: Command,       chars: "\x02\x68" }
  - { key: "RBracket", mods: Command,       chars: "\x02\x6c" }
