import:
  - ~/.alacritty.common.yml
font:
  size: 13
key_bindings:
  - { key: N, mods: Command, action: SpawnNewInstance }

  # tmux key binding
  - { key: D, mods: Command, chars: "\x02\x76" }
  - { key: D, mods: Command|Shift, chars: "\x02\x73" }
  - { key: W, mods: Command, chars: "\x02\x78" }
  - { key: H, mods: Command, chars: "\x02\x68" }
  - { key: J, mods: Command, chars: "\x02\x6a" }
  - { key: K, mods: Command, chars: "\x02\x6b" }
  - { key: L, mods: Command, chars: "\x02\x6c" }
  - { key: T, mods: Command, chars: "\x02\x63" }
  - { key: Key1, mods: Command, chars: "\x02\x31" }
  - { key: Key2, mods: Command, chars: "\x02\x32" }
  - { key: Key3, mods: Command, chars: "\x02\x33" }
  - { key: Key4, mods: Command, chars: "\x02\x34" }
  - { key: Key5, mods: Command, chars: "\x02\x35" }
  - { key: Key6, mods: Command, chars: "\x02\x36" }
  - { key: Key7, mods: Command, chars: "\x02\x37" }
  - { key: Key8, mods: Command, chars: "\x02\x38" }
  - { key: Key9, mods: Command, chars: "\x02\x39" }
  - { key: Left, mods: Command, chars: "\x02\x48" }
  - { key: Down, mods: Command, chars: "\x02\x4a" }
  - { key: Up, mods: Command, chars: "\x02\x4b" }
  - { key: Right, mods: Command, chars: "\x02\x4c" }
  - { key: "LBracket", mods: Command,       chars: "\x02\x68" }
  - { key: "RBracket", mods: Command,       chars: "\x02\x6c" }
