cask_args appdir: "~/Applications"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

tap "homebrew/bundle"
tap "hashicorp/tap"

tap "derailed/k9s"
tap "bufbuild/buf"

brew "telnet"
brew "gnu-sed"
brew "procs"
brew "htop"

brew "mas"

cask "alacritty"
cask "dropbox"
cask "google-chrome"
cask "telegram"
cask "firefox"
cask "keepassxc"
cask "eqmac"

mas "Blackmagic Disk Speed Test", id: 425264550
