cask_args appdir: "/Applications"

# core
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "hashicorp/tap"
tap "wez/wezterm"

# extras
tap "AdoptOpenJDK/openjdk"
tap "derailed/k9s"
tap "bufbuild/buf"


brew "ccache"
brew "cmake"
brew "coreutils"
brew "curl"

# core utils
brew "ripgrep"
brew "telnet"
brew "exa"
brew "bat"
brew "fd"
brew "wget"
brew "jq"
brew "htop"
brew "fzf"
brew "git"
brew "git-lfs"

brew "gnupg"

# cloud tools
brew "helm"
brew "protobuf"
brew "kubernetes-cli"
brew "kustomize"
brew "krew"
brew "derailed/k9s/k9s"
brew "podman"

# terminal
brew "tmux"
brew "direnv"
brew "starship"
brew "zoxide"
brew "zsh"
brew "neovim"
brew "git-delta"
brew "jesseduffield/lazygit/lazygit"
brew "gnu-sed"
brew "fd"
brew "grpcurl"

# langluage
brew "python@3.10"
brew "go"
cask "adoptopenjdk11"
cask "adoptopenjdk/openjdk/adoptopenjdk8"
brew "node@16"

brew "bufbuild/buf/buf"

brew "rust-analyzer"
brew "sccache"

brew "hugo"
brew "ncdu"

# securityes
brew "dnscrypt-proxy"

cask "wez/wezterm/wezterm"
cask "telegram"
cask "cloudflare-warp"
cask "calibre"
cask "dropbox"
cask "visual-studio-code"
cask "google-chrome"
cask "intellij-idea-ce"
cask "tableplus"
