#!/usr/bin/env bash

set -x

VERSION=$1
VERSION=${VERSION:-3.3.4}

DST="$APP_HOME/flutter"
rm -rf $DST
mkdir -p $DST

TMPDILE=/tmp/flutter.tar.xz
rm -f ${TMPDILE}
curl -fSL -o $TMPDILE https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${VERSION}-stable.tar.xz
tar -xf $TMPDILE --strip-components=1 -C $DST

ln -sf $DST/bin/flutter $HOME/.local/bin
rm -f $TMPDILE
