#!/usr/bin/env bash

VERSION=$1
VERSION=${VERSION:-0.11.0}
WORKDIR=/tmp/ipfs
rm -rf $WORKDIR
mkdir -p $WORKDIR
echo "Downloading ipfs ${VERSION} to ${WORKDIR}"
curl -fSL https://dist.ipfs.io/go-ipfs/v${VERSION}/go-ipfs_v${VERSION}_linux-amd64.tar.gz | tar xz --strip-components=1 -C $WORKDIR

echo "Installing"
sudo mv $WORKDIR/ipfs /usr/local/bin
