#!/usr/bin/env bash


VERSION=$1
VERSION=${VERSION:-1.3.7}

DST=/opt/rke

if [ ! -d ${DST} ]; then
  echo "Creating Install Dir at ${DST}"
  sudo mkdir -p $DST
  sudo chown -R $(whoami) $DST
fi

mkdir -p ${DST}/bin
BIN=${DST}/bin/rke

echo "downloading to ${BIN}"

curl -Lo $BIN https://github.com/rancher/rke/releases/download/v${VERSION}/rke_linux-amd64
chmod +x $BIN

echo "symlink to PATH"
ln -sf $BIN $HOME/.local/bin/rke
echo "Done!"
