#!/usr/bin/env bash

release_ver=$(curl -L -s https://dl.k8s.io/release/stable.txt)
DST=/usr/local/bin/kubectl

sudo curl -Lo $DST "https://dl.k8s.io/release/${release_ver}/bin/linux/amd64/kubectl"
sudo chmod +x $DST

echo "$(curl -Ls https://dl.k8s.io/${release_ver}/bin/linux/amd64/kubectl.sha256) ${DST}" | sha256sum --check

