#!/usr/bin/env bash
set -e

PROTOC_VERSION=$1
PROTOC_VERSION=${PROTOC_VERSION:-3.19.1}
echo "Installing protoc ${PROTOC_VERSION}"
rm -rf /tmp/protoc && mkdir -p /tmp/protoc && cd /tmp/protoc/
curl -sLo /tmp/protoc/proc.zip  https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
unzip /tmp/protoc/proc.zip
rm -f /tmp/protoc/proc.zip
sudo rm -rf /opt/protoc
sudo mkdir -p /opt/protoc
sudo mv * /opt/protoc
sudo chmod +x /opt/protoc/bin/protoc
sudo ln -sf /opt/protoc/bin/protoc /usr/local/bin/protoc
echo "Done $(protoc --version)"
