fallback = ''

[matching]
'discord' = ''
'balena-etcher' = ''
'Chia Blockchain' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'google-chrome' = ''
'/chrome.*/' = ''
'Chromium' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'jetbrains-studio' = ''
'/.*Spotify.*/' = ''
'GitHub Desktop' = ''
'/(?i)Github.*Firefox/' = ''
'/(?i)Youtube.*/' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/.*vim.*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'Alacritty' = ''
'org.keepassxc.KeePassXC'=""
'/.*Telegram.*/'=''
'/.*Notion.*/'='N'
'/.*Slack.*/'=''
'evince' = ''
'/.*Joplin.*/'='J'
'/.*calibre.*/'=''
'/.*Bluetooth.*/' = ''
'blueman-applet' = ''
'/.*Visual Studio.*/' = ''
"Microsoft-edge"=''
"microsoft-edge"=''
'obsidian'=''
