fallback = ''

[matching]
'balena-etcher' = ''
'Chia Blockchain' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = '󰷉'
'Insomnia' = ''
'Bitwarden' = ''
'google-chrome' = ''
'brave-browser'=''
'/chrome.*/' = ''
'Chromium' = ''
'Slack' = ''
'Code' = '󰨞'
'code-oss' = '󰨞'
'code-url-handler' = '󰨞'
'jetbrains-studio' = ''
'jetbrains-idea-ce'=''
'/.*Spotify.*/' = ''
'GitHub Desktop' = ''
'/(?i)Github.*Firefox/' = ''
'/(?i)Youtube.*/' = ''
'/(?i)Kubernetes.*/' = '󱃾'
'firefox' = '󰈹'
'/.*Firefox.*/' = '󰈹'
'/.*Vivaldi.*/' = '󰜫'
'Nightly' = '󰈹'
'firefox-aurora'=''
'firefoxdeveloperedition' = ''
'/.*vim.*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'Alacritty' = ''
"alacritty" = ""
"gnome-terminal-server" = ""
'org.keepassxc.KeePassXC'=""
'/.*Telegram.*/'=''
'/.*Notion.*/'='N'
'/.*Slack.*/'=''
'evince' = ''
'/.*Joplin.*/'='󰈄'
'/.*calibre.*/'=''
'/.*Bluetooth.*/' = ''
'blueman-applet' = ''
'/.*Visual Studio.*/' = ''
"Microsoft-edge"=''
"microsoft-edge"=''
'obsidian'='󱞂'
"Logseq"=''
"Zotero"=""
"libreoffice-writer"=""
"libreoffice-calc"="󱎏"
"libreoffice-startcenter"="󰏆"
"pdfarrange"=""
"file manager" = ""
"org.gnome.Nautilus" = ""
"github" = ""
"rust" = ""
"google" = ""
"go" = ""
"private browsing" = ""
"chrome" = ""
"calculator" = ""
"transmission" = ""
"videostream" = ""
"mpv" = ""
"music" = ""
"disk usage" = "󰨣"
".pdf" = ""
"rhythmbox"=""
"/.*Cryptomator.*/" = "󱇱"
"/.*Microsoft Teams.*/" = "󰊻"
"/.*Workplace.*/" = "󰬱"
"org.wezfurlong.wezterm" = "" 
"/.*DBeaver.*/" = ""
"/.*Outlook.*/" = "󰴢"
"/.*CADS.*/" = "󱘮"
"sublime_text"=""
"org.gnome.clocks"=""
"/.*Virtual Machine.*/"=""
"/.*win.*/"=""
