import = ["/Users/hienduyph/.alacritty.common.toml"]

[font]
size = 9.6

[font.normal]
family = "JetBrainsMono NF"
style = "Light"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Option"
