font:
  size: 9
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Light
key_bindings:
  - { key: N,     mods: Option,       action: SpawnNewInstance }
shell:
  program: /usr/bin/tmux
  args:
    - new-session
    - -A
    - -s
    - Lala
