env:
  TERM: xterm-256color
shell:
  program: /bin/sh
  args:
    - -l
    - -c
    - tmux new-session -A -s Lala
window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 0
    y: 0
  startup_mode: Maximized
  decorations: none
  dynamic_padding: true
scrolling:
  history: 10000
  multiplier: 3
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Light
  bold:
    family: JetBrainsMono Nerd Font
    style: Regular
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  size: 13
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
draw_bold_text_with_bright_colors: true
colors:
  # Default colors
  primary:
    background: '0xffffff'
    foreground: '0x586069'

  # Normal colors
  normal:
    black:   '0x697179'
    red:     '0xd03d3d'
    green:   '0x14ce14'
    yellow:  '0x949800'
    blue:    '0x0451a5'
    magenta: '0xbc05bc'
    cyan:    '0x0598bc'
    white:   '0x586069'

  # Bright colors
  bright:
    black:   '0x666666'
    red:     '0xcd3131'
    green:   '0x14ce14'
    yellow:  '0xb5ba00'
    blue:    '0x0451a5'
    magenta: '0xbc05bc'
    cyan:    '0x0598bc'
    white:   '0x586069'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xcd3131' }
bell:
  animation: EaseOutExpo
  duration: 0
mouse_bindings:
  - mouse: Middle
    action: PasteSelection
mouse:
  double_click:
    threshold: 300
  triple_click:
    threshold: 300
  hide_when_typing: true
cursor:
  style: Block
  unfocused_hollow: true
live_config_reload: true
key_bindings:
  - { key: N,     mods: Option,       action: SpawnNewInstance }
  - { key: D,     mods: Option,       chars: "\x02\x76" }
  - { key: D,     mods: Option|Shift, chars: "\x02\x73" }
  - { key: W,     mods: Option,       chars: "\x02\x78" }
  - { key: H,     mods: Option,       chars: "\x02\x68" }
  - { key: J,     mods: Option,       chars: "\x02\x6a" }
  - { key: K,     mods: Option,       chars: "\x02\x6b" }
  - { key: L,     mods: Option,       chars: "\x02\x6c" }
  - { key: T,     mods: Option,       chars: "\x02\x63" }
  - { key: Key1,  mods: Option,       chars: "\x02\x31" }
  - { key: Key2,  mods: Option,       chars: "\x02\x32" }
  - { key: Key3,  mods: Option,       chars: "\x02\x33" }
  - { key: Key4,  mods: Option,       chars: "\x02\x34" }
  - { key: Key5,  mods: Option,       chars: "\x02\x35" }
  - { key: Key6,  mods: Option,       chars: "\x02\x36" }
  - { key: Key7,  mods: Option,       chars: "\x02\x37" }
  - { key: Key8,  mods: Option,       chars: "\x02\x38" }
  - { key: Key9,  mods: Option,       chars: "\x02\x39" }
  - { key: Left,  mods: Option,       chars: "\x02\x48" }
  - { key: Down,  mods: Option,       chars: "\x02\x4a" }
  - { key: Up,    mods: Option,       chars: "\x02\x4b" }
  - { key: Right, mods: Option,       chars: "\x02\x4c" }
  - { key: "LBracket", mods: Option,       chars: "\x02\x68" }
  - { key: "RBracket", mods: Option,       chars: "\x02\x6c" }
